CREATE TABLE minions (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(50) NOT NULL,
age INT(3),
town_id INT(11) NOT NULL);
CREATE TABLE towns (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(50) NOT NULL);